apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  controlPlaneEndpoint:
    host: apiserver
    port: 443
