apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ include "cluster.name" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    {{- include "cluster-azure-chart.labels" . | nindent 4 }}
spec:
  location: {{ .Values.location }}
  resourceGroup: {{ include "cluster.name" . }}
