apiVersion: v1
entries:
  cluster-azure-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-31T14:45:17.670596389+02:00"
    description: A Helm chart for Kubernetes
    digest: af11f738f75287e95246ebf945e62868bf37eab5ddede893f42e951a4696b2ff
    name: cluster-azure-chart
    type: application
    urls:
    - https://nprokopic.github.io/helm-playground/charts/cluster-azure-chart-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-31T14:45:17.670435254+02:00"
    description: A Helm chart for Kubernetes
    digest: 0405b8583aec47135a1d4f3f20281f30a31e17b48b211f1dd7043b4c609e4acc
    name: cluster-azure-chart
    type: application
    urls:
    - https://nprokopic.github.io/helm-playground/charts/cluster-azure-chart-0.1.0.tgz
    version: 0.1.0
  cluster-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-31T14:45:17.670749755+02:00"
    description: A Helm chart for Kubernetes
    digest: fa0bc4b21e59ea25e1b4b2029281f193be1ffa79f76daf8401a9c2ef876f42db
    name: cluster-chart
    type: application
    urls:
    - https://nprokopic.github.io/helm-playground/charts/cluster-chart-0.1.0.tgz
    version: 0.1.0
generated: "2023-08-31T14:45:17.670164321+02:00"
