apiVersion: v1
entries:
  cluster-azure-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-31T13:45:30.894719615+02:00"
    description: A Helm chart for Kubernetes
    digest: af11f738f75287e95246ebf945e62868bf37eab5ddede893f42e951a4696b2ff
    name: cluster-azure-chart
    type: application
    urls:
    - https://nprokopic.github.io/helm-playground/charts/cluster-azure-chart-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-31T13:45:30.894546713+02:00"
    description: A Helm chart for Kubernetes
    digest: 0405b8583aec47135a1d4f3f20281f30a31e17b48b211f1dd7043b4c609e4acc
    name: cluster-azure-chart
    type: application
    urls:
    - https://nprokopic.github.io/helm-playground/charts/cluster-azure-chart-0.1.0.tgz
    version: 0.1.0
generated: "2023-08-31T13:45:30.894227503+02:00"
