apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  annotations:
    global-name: {{ .Values.global.metadata1.name }}
    exported-name: {{ .Values.exports.metadata2.name }}
    local-name: {{ .Values.metadata3.name }}
spec:
  controlPlaneEndpoint:
    host: apiserver
    port: 443
